# Generated by Django 4.1.7 on 2023-03-08 09:37

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('profile_pic', models.ImageField(default='users/profile_pics/default.jpg', upload_to='users/profile_pics')),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('home_address', models.CharField(default='', max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, default='POINT(0 0)', geography=True, null=True, srid=4326)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
